# Generated by Django 5.1 on 2025-11-20 00:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_producto_en_promocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='repartidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_asignados', to='core.repartidor'),
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(help_text='Calificación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional sobre el producto', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('compra_verificada', models.BooleanField(default=False, help_text='Indica si el cliente compró el producto')),
                ('cliente', models.ForeignKey(limit_choices_to={'rol': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='core.producto')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['producto', '-fecha_creacion'], name='core_resena_product_9b2428_idx')],
                'unique_together': {('producto', 'cliente')},
            },
        ),
    ]
