# Generated by Django 5.1 on 2025-11-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_pedido_repartidor_resena'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, help_text='Solo para ventas POS. Escanea el código o escribelo', max_length=50, null=True, unique=True, verbose_name='SKU/Código de Barras (Opcional)'),
        ),
    ]
